---
title: "Session 1.1: Descriptive statistics"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
bibliography: textanalysis.bib
---

This section will focus on to systematize and extract information from historical sources, regardless this information is **categorical**, **ordinal** and **numerical**. Displaying frequency tables, plotting histograms and reporting summary statistics (i.e. the mean, the minimum and maximum values, the standard deviation, etc.) helps characterising how our data looks like. 

As well as considering just one variable at a time (**univariate statistics**) and then move on to talk about several variables simultaneously (**bivariate statistics**). Making sense of the source using descriptive statistics can actually get you a long way in your understanding of the historical setting you are studying. 

In the process, we will also learn how to restrict the analysis to particular subsamples of our data and to prepare the data set for subsequent analyses. Apart from correcting potential typos and errors derived from digitising the original source into a dataset, this includes re-categorisation, that is, defining the categories within which each observation is classified. 

### Download the following for this session:

#### Scripts:

1. [Qualitative info](scripts/1_1_desc_qual.R)

2. [Numerical info](scripts/1_2_desc_num.R)

3. [Bivariate statistics](scripts/1_3_desc_bivar.R)

#### Data:

1. [Paisley dataset](data/paisley_data.xls)

2. [Paisley dataset (v2)](data/paisley_v2.rds)

3. [Education 1860 (Spanish districts)](data/educ_1860.xlsx)

