---
title: 'Session 1.2: Collecting, reading and cleaning text data'
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
bibliography: textanalysis.bib
---

### Session overview

In this session we will learn how to read texts into R. We will see how to handle files in .doc, .html, and machine-readable .pdf files. These are the easiest case scenarios. We will then move on to .pdf files that are challenging because of their layouts and then discuss strategies for digitizing PDFs that are not yet machine-readable. We will finally motion towards web scrapping of text data and point you towards what is possible and tools that can be used to gather text data from the web.

The second major goal of this session is to consider how to handle text in R. We will go further into regular expressions (those of you who have done the tutorial will have already encountered some of this) and then learn common techniques for cleaning up text in R and formatting it so that it is in a condition we can begin to do some text analysis on. Using tools of data frame manipulation we will then learn one method for creating Google n-gram-style graphs.

### Download the following for this session

[Script for this session](scripts/Day1-reading-cleaning.R).

Four Charles Dickens novels can be downloaded [here](data/dickens/A Christmas Carol - Charles Dickens - 1843.pdf), [here](data/dickens/David Copperfield - Charles Dickens - 1850.txt), [here](docs/data/dickens/Hard Times - Charles Dickens - 1854.docx), and [here](data/dickens/Oliver Twist - Charles Dickens - 1838.html). Put these in a separate folder within your working drive, preferably with a name that is easy to type.

We will also be working with some examples of historical documents. Download these (probably easiest to save them to your working directory):

* [Sample Stortings melding from 1960-61](data/stmeld8_kongo.pdf).

* [Statoil's 2001 Sustainability Report](https://www.equinor.com/sustainability/sustainability-reports-archive) (also [here](data/sustainability-report-2001-equinor.pdf))

* [King Haakons 1925 speech to the Norwegian parliament](data/Storting_KongHaakon_1925.pdf)

Finally we will begin to work with two sample corpora that we will continue to use over the next week:

* [Nobel Peace Prize award speeches](data/NobelPeace.csv).
Nobel Peace Prize award ceremony speeches since 1905. They are scraped from https://www.nobelprize.org with no cleaning or improvements so that we can practice all steps of the process and see the advantages and potential problems in working with digital corpora. Saved as a csv-file.

* [Sustainability reports of major oil corporation]([here](data/srps.csv). 
These reports were downloaded by hand from the companies' respective websites, digitized using pdftabula and saved as a csv-file.