---
title: "Session 3.2: Topic modeling"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
bibliography: textanalysis.bib
---

### Session overview

Topic models are some of the most well-known algorithms in digital humanities. While in computer science and machine learning they are a decided old technology, in many areas of the humanities they still feel new and cutting edge. 

We will begin the session with a short examination of what topic models actually are. Building on the argument that historians, and digital humanists in general, should understand how algorithms represent and transformation text but not necessarily the means by which the algorithms calculate their conclusions @schmidt2016digital, we begin with a high-level overview of what a bag-of-words model entails, how this enables document vectorization, and finally what a topic model. We will then look at implementation of topic models in two widely used R packages.

### Download the following for this session

[Script for this session](scripts/Day3-vectorization-topic-models.R).