---
title: "Quantifying History"
subtitle: "Norwegian Research School in History, NTNU, Trondheim"
author: Francisco Beltrán Tapia^[NTNU, francisco.beltran.tapia@ntnu.no] and Gregory Ferguson-Cradler^[INN, gregory.fergusoncradler@inn.no]
date: "February 3-7, 2025"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
# bibliography: textanalysis_general.bib
# nocite: '@*'
---

<!-- To render whole site: rmarkdown::render_site() -->

# Overview

How can quantitative methods allow historians to make sense of the ever-increasing wealth of digitized sources, both numeric and textual? How can historians use quantitative and computational methods to gain a better overview of their source base, ask new questions, and supplement and enhance close reading? 

This course provides an in-depth introduction to quantitative and computational methods, covering some of the techniques most widely used in research in the historical and social sciences. The hands-on course will teach students to apply basic quantitative methods to real historical information, both quantitative and qualitative, as well as equip them with the necessary background to understand and interpret the historical literature using these methods. 

No background in statistics is required and statistical theory and mathematics will be kept to a minimum. The goal is to provide students with the tools to critically engage with the literature relying on quantitative methods and to be able to conduct original research using these tools in academia, the public sector, or business. In the process, students will learn basic programming skills in R, a statistical software widely used by practitioners in many different fields both inside and outside academia. 

# Goals

The course revolves around two main themes: 

- classic statistical methods: descriptive statistics, correlation and regression analysis. 
- computational content analysis: natural language processing (including word frequency, dictionary methods, text classification), topic models, digital corpus management and web scraping.

Taught intensively over five days, the course is structured into 10 three-hour sessions combining lectures (approx. 1 hour) and applied sessions behind a computer (approx. 2 hours). Students will learn by applying the different concepts to real data used by historians.

Apart from actively participating in the sessions, students are expected to deliver a take-home assignment after the course is finished. A candidate who satisfactorily passes the course will be able to: 

  * Critically engage with studies relying on quantitative methods. 
  * Conduct original research using these tools in academia, the public, or the business sector. 
  * Continue to develop skills in quantitative methods based on the foundations provided in this course.
  * Acquire basic competence in R, a statistical software widely used by practitioners in many fields.


# Pre-requisites

The only required reading prior to the course is an introductory text that will be distributed by email.

We will be using R, a widely popular statistical software, which has the added advantage of being free. Please download it in your laptops before coming to Trondheim. In addition, we strongly encourage to complete a short sequence of tutorials to smooth the learning curve, so you are not completely new to the software before the course starts. Instructions for installing R, RStudio, and R tutorials are [here](TutorialInstructions.pdf).

List of packages to be used with normal R installation: tidyverse, readtext, lubridate, rvest, tidytext, stopwords, SnowballC, widyr, quanteda, writexl, textstem, koRpus.lang.en, koRpus, sylly, wordcloud, wordcloud2, RColorBrewer, entity, udpipe, textdata, quanteda.textstats, topicmodels, stm, shiny, miniUI


List of packages with more difficult R installation and maybe links to troubleshooting pages: 
- tubulapdf (https://docs.ropensci.org/tabulapdf/)



<!-- # Practicalities -->

<!-- The following script will install (if not already installed) and load all packages used in this tutorial. (there's bound to be a couple we've forgotten, we'll add these as we go). -->

<!-- ```{r, eval = FALSE} -->
<!-- if (!requireNamespace("xfun")) install.packages("xfun") -->
<!-- xfun::pkg_attach2("tidyverse", "lubridate", "rvest", "stringr", "readtext", "tesseract", "tidytext", "SnowballC", "wordcloud", "wordcloud2", "widyr", "quanteda", "quanteda.textstats", "magrittr", "pdftools", "devtools", "tsne", "topicmodels", "readtext") -->
<!-- # The following two packages have Java dependencies that might give some (especially Windows) machines trouble. No worries if they don't load on your computer, we will demonstrate running them on RStudio Cloud. -->
<!-- xfun::pkg_attach2("tabulizer", "openNLP") -->
<!-- install.packages("devtools") -->
<!-- devtools::install_github("bmschmidt/wordVectors") -->
<!-- ``` -->

<!-- If you have problems installing `tabulizer`, see [these](https://github.com/ropensci/tabulizer) other options and troubleshooting techniques. -->

<!-- # References and Sources -->
